# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-added-large-files
    -   id: check-json
    -   id: check-shebang-scripts-are-executable
    -   id: check-xml
    -   id: check-yaml
-   repo: https://github.com/psf/black
    # Use same version as in setup.py
    rev: 22.8.0
    hooks:
    -   id: black
        args:
          - --line-length=79
-   repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
    -   id: flake8
