# readthedocs.yml

# See
# - https://docs.readthedocs.io/en/stable/config-file/index.html
# - https://docs.readthedocs.io/en/latest/yaml-config.html
# - https://docs.readthedocs.io/en/latest/config-file/v2.html
# - https://github.com/rtfd/readthedocs.org/issues/2139
# - https://docs.readthedocs.io/en/latest/guides/build-using-too-many-resources.html
# - https://docs.readthedocs.io/en/latest/config-file/v2.html#python-system-packages

version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.8"

python:
  install:
    - method: pip
      path: .
  system_packages: true

formats: []
