os: linux
dist: bionic
language: python
python:
    - "3.6"

jobs:
  include:
    - stage: "installing pip packages and running tests"
      before_install:
        # Travis installs pipenv by default. We don't need it
        - pip3 uninstall --yes pipenv
      script: travis_scripts/pip_install_and_tests
