---
# yamllint disable rule:line-length
name: crateanon
version: 0.1.0
description: "CRATE: Clinical Records Anonymisation and Text Extraction"
registry: crateanon

required:
  - docker

mixins:
  - docker:
      clientVersion: 20.10.7
  - docker-compose:
      clientVersion: 1.29.2
  - exec

print-demo-crateweb-config-file:
  - docker-compose:
      description: "Print demo crateweb config file"
      arguments:
        - run
        - --rm crate_workers
        - /bin/bash -c "source /crate/venv/bin/activate; crate_print_demo_crateweb_config > $CRATE_WEB_LOCAL_SETTINGS"

django-manage-migrate:
  - docker-compose:
      description: "Create the database structure"
      arguments:
        - run
        - --rm crate_workers
        - /bin/bash -c "source /crate/venv/bin/activate; crate_django_manage migrate"

install:
  - docker-compose:
      description: Docker Compose up
      arguments:
        - up
        - --abort-on-container-exit

uninstall:
  - docker-compose:
      description: Docker Compose down
      arguments:
        - down
        - --remove-orphans

parameters:
  - name: crate_docker_config_host_dir
    type: string
    env: CRATE_DOCKER_CONFIG_HOST_DIR

  - name: crate_docker_gate_bioyodie_resources_host_dir
    type: string
    env: CRATE_DOCKER_GATE_BIOYODIE_RESOURCES_HOST_DIR

  - name: crate_docker_mysql_host_port
    type: integer
    env: CRATE_DOCKER_MYSQL_HOST_PORT

credentials:
  - name: crate_docker_mysql_crate_user_password
    type: string
    env: CRATE_DOCKER_MYSQL_CRATE_USER_PASSWORD

  - name: crate_docker_mysql_root_password
    type: string
    env: CRATE_DOCKER_MYSQL_ROOT_PASSWORD
