---
# yamllint disable rule:line-length
name: Docker
# yamllint disable-line rule:truthy
on:
    push:
        paths:
            - 'crate_anon/**'
            - .github/workflows/docker.yml
            - github_action_scripts/docker.sh
            - 'docker/**'
            - setup.py
jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Build
              run: ${GITHUB_WORKSPACE}/github_action_scripts/docker.sh
