---
# yamllint disable rule:line-length
name: Installer
# yamllint disable-line rule:truthy
on:
    push:
        paths:
            - 'crate_anon/**'
            - .github/workflows/installer.yml
            - github_action_scripts/installer_setup.sh
            - github_action_scripts/post_installation_checks.sh
            - 'docker/**'
            - 'installer/**'
            - setup.py
jobs:
    installer:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Run installer
              run: |
                set -eux -o pipefail
                ${GITHUB_WORKSPACE}/github_action_scripts/installer_setup.sh
                cd ${GITHUB_WORKSPACE}/installer
                ./installer.sh -d
                export CRATE_HOME=${GITHUB_WORKSPACE}
                ${GITHUB_WORKSPACE}/github_action_scripts/post_installation_checks.sh
