---
# yamllint disable rule:line-length
name: Installer
# yamllint disable-line rule:truthy
on:
    push:
        paths:
            - 'crate_anon/**'
            - .github/workflows/installer.yml
            - github_action_scripts/installer_setup.sh
            - github_action_scripts/post_installation_checks.sh
            - github_action_scripts/set_crate_docker_environment
            - 'docker/**'
            - 'installer/**'
            - setup.py
jobs:
    installer:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v3
            - name: Run installer
              run: |
                set -eux -o pipefail
                echo "HOME is ${HOME}"
                echo "GITHUB_WORKSPACE is ${GITHUB_WORKSPACE}"
                echo "CRATE_DOCKER_CONFIG_HOST_DIR is ${CRATE_DOCKER_CONFIG_HOST_DIR}"
                source ${GITHUB_WORKSPACE}/github_action_scripts/set_crate_docker_environment
                ${GITHUB_WORKSPACE}/github_action_scripts/installer_setup.sh
                cd ${GITHUB_WORKSPACE}/installer
                ./installer.sh -d
                export CRATE_HOME=${GITHUB_WORKSPACE}
                ${GITHUB_WORKSPACE}/github_action_scripts/post_installation_checks.sh
