---
# yamllint disable rule:line-length
name: Installer
# yamllint disable-line rule:truthy
on:
    push:
        paths:
            - 'crate_anon/**'
            - .github/workflows/installer.yml
            - 'docker/**'
            - 'installer/**'
            - setup.py
jobs:
    installer:
        runs-on: ubuntu-latest
        steps:
            - name: Build
              run: |
                  set -euxo pipefail
                  sudo apt-get update
                  sudo apt -y install python3-virtualenv python3-venv
                  docker --version
                  export CRATE_DOCKER_MYSQL_CRATE_HOST_PORT=3307
                  export CRATE_DOCKER_CONFIG_HOST_DIR=${HOME}/crate_config
                  export CRATE_DOCKER_GATE_BIOYODIE_RESOURCES_HOST_DIR=${HOME}/bioyodie_resources
                  export CRATE_DOCKER_MYSQL_CRATE_USER_PASSWORD=ramalamadingdong
                  export CRATE_DOCKER_MYSQL_CRATE_ROOT_PASSWORD=shoobydoobydoo
                  export CRATE_DOCKER_CRATEWEB_SUPERUSER_USERNAME=admin
                  export CRATE_DOCKER_CRATEWEB_SUPERUSER_PASSWORD=servisolironcamera
                  export CRATE_DOCKER_CRATEWEB_SUPERUSER_EMAIL=admin@example.com
                  export CRATE_DOCKER_CRATEWEB_HOST_PORT=8000
                  export CRATE_DOCKER_CRATEWEB_USE_HTTPS=0
                  # Production:
                  # curl -L https://github.com/RudolfCardinal/crate/releases/latest/download/installer.sh | bash
                  # Development:
                  curl -L --retry 10 --fail https://github.com/RudolfCardinal/crate/releases/download/installer-test-7/installer.sh | bash
                  # Check Django app is running
                  cd ${HOME}/crate/docker/dockerfiles
                  docker compose logs
                  SERVER_IP=$(docker inspect crate_crate_server --format='{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}')
                  curl -I -L --retry 10 --retry-connrefused --fail $SERVER_IP:8000/crate/
                  curl -I -L --fail $SERVER_IP:8000/crate_static/scrubber.png
                  cd ${HOME}/crate/docker/dockerfiles
                  # Check anonymiser worked
                  anonymised=$(docker compose exec -T research_db mysql -Ns -u research -presearch research -e "SELECT SUBSTR(note, 1, 36) FROM note LIMIT 1")
                  [ "${anonymised}" = "\n[__PPP__] [__PPP__] lived on a farm" ]
