---
# yamllint disable rule:line-length
name: Installer
# yamllint disable-line rule:truthy
on:
    push:
        paths:
            - 'crate_anon/**'
            - .github/workflows/installer.yml
            - 'docker/**'
            - 'installer/**'
            - setup.py
jobs:
    installer:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Run installer
              run: |
                  set -euxo pipefail
                  sudo apt-get update
                  sudo apt -y install python3-virtualenv python3-venv wait-for-it
                  docker --version
                  docker compose version
                  export CRATE_DOCKER_MYSQL_CRATE_HOST_PORT=3307
                  export CRATE_DOCKER_CONFIG_HOST_DIR=${HOME}/crate_config
                  export CRATE_DOCKER_GATE_BIOYODIE_RESOURCES_HOST_DIR=${HOME}/bioyodie_resources
                  export CRATE_DOCKER_MYSQL_CRATE_USER_PASSWORD=ramalamadingdong
                  export CRATE_DOCKER_MYSQL_CRATE_ROOT_PASSWORD=shoobydoobydoo
                  export CRATE_DOCKER_CRATEWEB_SUPERUSER_USERNAME=admin
                  export CRATE_DOCKER_CRATEWEB_SUPERUSER_PASSWORD=servisolironcamera
                  export CRATE_DOCKER_CRATEWEB_SUPERUSER_EMAIL=admin@example.com
                  export CRATE_DOCKER_CRATEWEB_HOST_PORT=8000
                  export CRATE_DOCKER_CRATEWEB_USE_HTTPS=0
                  mkdir ${CRATE_DOCKER_CONFIG_HOST_DIR}
                  cd ${GITHUB_WORKSPACE}/installer
                  ./installer.sh -d
                  # Check Django app is running
                  cd ${GITHUB_WORKSPACE}/docker/dockerfiles
                  docker compose logs
                  SERVER_IP=$(docker inspect crate_crate_server --format='{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}')
                  wait-for-it $SERVER_IP:8000 --timeout=300
                  curl -I -L --retry 10 --fail $SERVER_IP:8000/crate/
                  # Check static files collected
                  curl -I -L --fail $SERVER_IP:8000/crate_static/scrubber.png
                  cd ${GITHUB_WORKSPACE}/docker/dockerfiles
                  # Check anonymiser worked
                  anonymised=$(docker compose exec -T research_db mysql -Ns -u research -presearch research -e "SELECT SUBSTR(note, 1, 36) FROM note LIMIT 1")
                  [ "${anonymised}" = "\n[__PPP__] [__PPP__] lived on a farm" ]
