---
# yamllint disable rule:line-length
name: Installer
# yamllint disable-line rule:truthy
on:
    push:
        paths:
            - 'crate_anon/**'
            - '!crate_anon/integration_tests'
            - .github/workflows/installer.yml
            - github_action_scripts/anonymisation_checks.sh
            - github_action_scripts/docker_db_setup.sh
            - github_action_scripts/installer_setup.sh
            - github_action_scripts/post_installation_checks.sh
            - github_action_scripts/set_crate_docker_environment
            - github_action_scripts/set_crate_docker_mysql_environment
            - github_action_scripts/source_database.sql
            - 'docker/**'
            - 'installer/**'
            - setup.py
jobs:
    installer:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v4
            - name: Run installer
              run: |
                set -eux -o pipefail
                DOCKER_CONFIG=${DOCKER_CONFIG:-$HOME/.docker}
                mkdir -p ${DOCKER_CONFIG}/cli-plugins
                docker version
                docker compose version
                source ${GITHUB_WORKSPACE}/github_action_scripts/set_crate_docker_environment
                ${GITHUB_WORKSPACE}/github_action_scripts/installer_setup.sh
                cd ${GITHUB_WORKSPACE}/installer
                ./installer.sh -d
                export CRATE_HOME=${GITHUB_WORKSPACE}
                ${GITHUB_WORKSPACE}/github_action_scripts/post_installation_checks.sh
                ${GITHUB_WORKSPACE}/github_action_scripts/anonymisation_checks.sh
                # Now do it again with external MySQL databases
                # docker-compose down --volumes with relevant docker-compose files
                ./installer.sh -d -p
                rm ${CRATE_DOCKER_CONFIG_HOST_DIR}/${CRATE_DOCKER_CRATEWEB_CONFIG_FILENAME}
                rm ${CRATE_DOCKER_CONFIG_HOST_DIR}/${CRATE_DOCKER_CRATE_ANON_CONFIG}
                source ${GITHUB_WORKSPACE}/github_action_scripts/set_crate_docker_mysql_environment
                ${GITHUB_WORKSPACE}/github_action_scripts/docker_db_setup.sh mysql 3306
                env
                ./installer.sh -d -v
                ${GITHUB_WORKSPACE}/github_action_scripts/post_installation_checks.sh
