---
# yamllint disable rule:line-length
name: Installer
# yamllint disable-line rule:truthy
on:
    push:
        paths:
            - 'crate_anon/**'
            - .github/workflows/installer.yml
            - 'docker/**'
            - 'installer/**'
jobs:
    installer:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Build
              run: |
                  set -euxo pipefail
                  sudo apt-get update
                  sudo apt -y install python3-virtualenv python3-venv
                  # TODO: wget this from releases as a normal user would
                  # and don't checkout above
                  cd installer
                  ./installer.sh
