---
# yamllint disable rule:line-length
name: Python checks
# yamllint disable-line rule:truthy
on:
    push:
        paths:
            - '**.py'
            - .github/workflows/python-checks.yml
jobs:
    pip-install-and-tests:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: [3.7, 3.8, 3.9]
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Pip install and tests
              run: |
                  set -xe
                  python -m venv ${HOME}/venv
                  source ${HOME}/venv/bin/activate
                  python -VV
                  python -m site
                  python -m pip install -U pip
                  echo dumping pre-installed packages
                  python -m pip freeze
                  echo installing pip packages
                  python -m pip install -e .
                  echo checking packages for conflicts
                  python -m pip check
                  echo installing vulnerability checker
                  python -m pip install safety
                  echo checking packages for vulnerabilities
                  # All of these vulnerabilities look either harmless or very low risk
                  # 44715 numpy fixed in 1.22 https://github.com/numpy/numpy/issues/19038
                  # 44716 numpy fixed in 1.22 https://github.com/numpy/numpy/issues/19000
                  # 44717 numpy fixed in 1.22 https://github.com/numpy/numpy/issues/18993
                  safety check --full-report -i 44715 -i 44716 -i 44717
                  echo checking python for style and errors
                  flake8 --config=setup.cfg crate_anon
                  echo running tests
                  pytest -v
