---
# yamllint disable rule:line-length
name: Python checks
# yamllint disable-line rule:truthy
on:
    push:
        paths:
            - '**.py'
            - .github/workflows/python-checks.yml
            - github_action_scripts/python_checks.sh
            - github_action_scripts/python_setup.sh
            - github_action_scripts/setup_redis.sh
jobs:
    pip-install-and-tests:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ["3.8", "3.9", "3.10"]
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Redis setup
              run: |
                set -euxo pipefail
                ${GITHUB_WORKSPACE}/github_action_scripts/setup_redis.sh
            - name: Pip install and tests
              run: |
                set -euxo pipefail
                ${GITHUB_WORKSPACE}/github_action_scripts/python_setup.sh
                ${GITHUB_WORKSPACE}/github_action_scripts/python_checks.sh
