---
# yamllint disable rule:line-length
name: Python checks
# yamllint disable-line rule:truthy
on:
    push:
        paths:
            - '**.py'
            - .github/workflows/python-checks.yml
            - github_action_scripts/python_checks.sh
jobs:
    pip-install-and-tests:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ["3.7", "3.8", "3.9", "3.10"]
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Pip install and tests
              run: ${GITHUB_WORKSPACE}/github_action_scripts/python_checks.sh
