---
name: Release
# yamllint disable-line rule:truthy
on:
    push:
        tags:
            - '*'

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v2
            - uses: ncipollo/release-action@v1
              with:
                  artifacts: "installer/installer.sh"
                  prerelease: true
                  token: ${{ secrets.GITHUB_TOKEN }}
