---
# yamllint disable rule:line-length
name: Release
# yamllint disable-line rule:truthy
on:
    push:
        tags:
            - '*'

jobs:
    release:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Check out repository
              uses: actions/checkout@v4
            - name: Work out tag
              id: vars
              run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
            - name: Create release with artifacts
              uses: ncipollo/release-action@v1
              with:
                  artifacts: "installer/installer_bootstrap.py"
                  token: ${{ secrets.GITHUB_TOKEN }}
            - name: Test installer
              run: |
                set -eux -o pipefail
                source ${GITHUB_WORKSPACE}/github_action_scripts/set_crate_installer_environment
                ${GITHUB_WORKSPACE}/github_action_scripts/installer_setup.sh
                cd ${HOME}
                curl -L --retry 10 --fail https://github.com/ucam-department-of-psychiatry/crate/releases/${{ steps.vars.outputs.tag }}/download/installer_bootstrap.py --output installer_bootstrap.py
                chmod u+x installer_bootstrap.py
                python3 installer_bootstrap.py --crate_root_dir /crate --version ${{ steps.vars.outputs.tag }}
                export CRATE_HOME=/crate/src
                ${GITHUB_WORKSPACE}/github_action_scripts/post_installation_checks.sh
